{% set name = "nifty-meta" %}
{% set version = "0.5.1" %}
#{% set sha256 = "b2ada6f86faf5c9032e8b1a7b8cc0dff68a229e90ad80b366f5564fec03caa17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../
  #fn: nifty_meta-{{ version }}.tar.gz
  #url: https://github.com/DerThorsten/nifty_meta/archive/{{ version }}.tar.gz
  #sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - toolchain
    - cmake


test:
  commands:
    - test -d ${PREFIX}/include/nifty/          # [unix]
    - test -d ${PREFIX}/include/nifty/meta  # [unix]
    - test -f ${PREFIX}/include/nifty_meta/meta.hpp  # [unix]
    - if exist %LIBRARY_PREFIX%\include\nifty\meta\meta.hpp (exit 0) else (exit 1)  # [win]


about:
  home: https://github.com/DerThorsten/nifty_meta
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'nifty-meta'
  description: 'nifty-meta'
  documentation_url:  https://github.com/DerThorsten/nifty_meta
  dev_url: https://github.com/DerThorsten/nifty_meta

extra:
  recipe-maintainers:
    - DerThorsten
